knp_paginator:
    page_range: 5                      # Nombre de pages affichées dans le sélecteur de pagination
    default_options:
        page_name: page                # Nom du paramètre de la page dans l'URL
        sort_field_name: sort          # Nom du paramètre pour le champ de tri dans l'URL
        sort_direction_name: direction # Nom du paramètre pour la direction de tri dans l'URL
        distinct: true                 # Utiliser DISTINCT pour le comptage des éléments (MySQL)
   # Chemin du modèle Twig pour la pagination
