#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# Exemple avec config/routes.yaml
admin_annonces_suppression:
    path: '/admin/annonce/suppression/{id}'
    controller: 'App\Controller\AdminController::suppressionAnnonce'
    methods: ['DELETE','POST']
